### ISSUE TITLE
Setting incorrect styles

### ISSUE THREAD

**Issue by FrencisAlreadyInUse** [JSxMachina/react-grid-system#57]
Refreshing the browser results in an incorrect rendering of the styles.
Even when explicitly firing *resize* on componentDidMount.

Reproduce issue:
https://github.com/FrencisAlreadyInUse/grid-system-issue

**Comment by buesing** [comment]
Just chiming in here as i'm working with @FrencisAlreadyInUse on the issue. Some more details:
We are using server rendering via next.js. The default server render class is `xl`. So when you open the index page of the example repo (https://github.com/FrencisAlreadyInUse/grid-system-issue/blob/master/pages/index.js) and size your browser to e.g. 400px, the Column component takes up 1 column as per the screen rendering class, so far everything as expected. 
In reality we are using a setup similar to here: https://github.com/JSxMachina/react-grid-system/issues/33
But there will be cases where the viewport size doesn't match whatever will be returned by the user agent string, for example a desktop at < 1024px width. To counter this problem we tried to fire a resize event to make the component re-render, but the styles don't seem to update. Only when resizing past a breakpoint the styles update. Any ideas?

**Comment by gerbenmeyer** [comment]
This seems to be caused by the new behavior of `ReactDOM.hydrate`, which won't try to patch up differences between the server and client render. Probably I'll have to add a `this.state.isClient` kind of behavior to react-grid-system, as is described at https://reactjs.org/docs/react-dom.html#hydrate.

**Comment by gerbenmeyer** [comment]
Just released version 4.0.0 of `react-grid-system`, in which this is fixed, among other things. It's a major version, because it has some breaking changes wrt. the grid configuration, as now it no longer uses the deprecated react context types.

**Comment by FrencisAlreadyInUse** [comment]
Thank you so much @gerbenmeyer ! True superhero :) Enjoy your day

**Comment by doskovicmilos** [comment]
hmm I use version 6.3.0 of react-grid-system and I still have the same problem :(
